### ISSUE TITLE
Not listing in browser

### ISSUE THREAD

**Issue by subhashsharma** [tadams42/flask-marshmallow-openapi#3]
When I integrate this project with my flask project, I can see the response in the Postman however not in the browser. 
This is the url I use `http://0.0.0.0:8001/v1/docs/static/swagger.json`

But it does work in Chrome

**Comment by tadams42** [comment]
`/v1/docs/static/swagger.json` is OpenAPI (SwaggerUI) data URL. This URL will always return HTTP response JSON with all the data needed to render docs. AFAIK, Chrome doesn't render JSON HTTP responses by default. Postman does.

Anyway, to see rendered the docs in Chrome use one of following URLs:

- `http://0.0.0.0:8001/v1/docs/swagger_ui`
- `http://0.0.0.0:8001/v1/docs/re_doc`
